### ISSUE TITLE
Update `tinyvec` to 1.0

### ISSUE THREAD

**Issue by Lokathor** [c410-f3r/cl-traits#2]
You should update your `tinyvec` usage to 1.0

Unfortunately, your CI is broken right now, so i don't want to throw more changes at you until you sort that out. However, for most people there's no break at all in practice compared to 0.3, so you should be able to just bump the number and go.

**Comment by c410-f3r** [comment]
Hello @Lokathor 

Thanks for pointing out a new release of `tinyvec`!
