### ISSUE TITLE
A fixed / updated 0.11.0 version of StaticVec is available, if you wanted to re-add it

### ISSUE THREAD

**Issue by slightlyoutofphase** [c410-f3r/cl-traits#3]
Not that you have to, of course. Just thought I'd let you know.

**Comment by c410-f3r** [comment]
Just re-added `staticvec`. Thanks @slightlyoutofphase !

**Comment by slightlyoutofphase** [comment]
Cool! My being unable to work on it for a while was quite unexpected, BTW - not likely to happen again, so I don't forsee any future long-term breakage.
